import http from 'node:http';
import {Machine,workflow} from '../lambda-machine.js';
import {startClock,chicagoDigits} from './clock-core.mjs';

const PORT=Number(process.env.PORT||8789);
const FAST_MS=Number(process.env.FAST_MS||125);
const RAW_MS=Number(process.env.RAW_MS||900);
const MAX_WIRE=Number(process.env.MAX_WIRE||1400);
const MAX_RAW=Number(process.env.MAX_RAW||36000);
const clients=new Set();

let cubeGen=null,cubeReq=null,cubeMachine=null,cubePhase='starting',cubeFrameNo=-1,cubeFrame=null;
let cubeBeta=0,cubeSteps=0,cubeRate=0,cubeRateBase=0,cubeRateAt=performance.now();
let clockState=startClock(),clockClosure=clockState.machine.control,clockTotalBeta=0,clockRate=0,clockRateBase=0,clockRateAt=performance.now();
let lastClockText=clockState.input.text;

function resetCube(){cubeGen=workflow();cubeReq=null;cubeMachine=null;cubePhase='starting';cubeFrameNo=-1;cubeFrame=null;cubeBeta=0;cubeSteps=0;cubeRate=0;cubeRateBase=0;cubeRateAt=performance.now();advanceCube();}
function advanceCube(value){for(;;){const n=cubeGen.next(value);value=undefined;if(n.done){cubeReq=null;cubeMachine=null;return;}const item=n.value;if(item.kind==='frame'){cubeFrameNo++;cubeFrame=serializeFrame(item.decoded);cubePhase=item.label;continue;}cubeReq=item;cubePhase=item.label;cubeMachine=new Machine(item.fn,item.args);return;}}
function stepCube(){if(!cubeMachine)return;const before=cubeMachine.beta,cont=cubeMachine.step();cubeSteps++;cubeBeta+=cubeMachine.beta-before;if(!cont){const result=cubeMachine.control;cubeMachine=null;advanceCube(result);}}
function stepClock(){const now=chicagoDigits();if(now.text!==lastClockText){lastClockText=now.text;clockState=startClock();clockClosure=clockState.machine.control;}if(clockState.done)return;const m=clockState.machine,before=m.beta,cont=m.step();clockState.steps++;clockState.beta+=m.beta-before;clockTotalBeta+=m.beta-before;clockClosure=m.control;if(!cont){clockState.done=true;clockClosure=m.control;}}

function serializeFrame(decoded){return{scale:String(decoded.scale),vertices:decoded.graph.vertices.map(v=>({id:v.id,coords:v.coords.map(String)})),edges:decoded.graph.edges};}
function stats(term){let nodes=0,vars=0,lams=0,apps=0,maxDepth=0;const s=[[term,0]];while(s.length){const[t,d]=s.pop();nodes++;maxDepth=Math.max(maxDepth,d);if(t.t==='v')vars++;else if(t.t==='l'){lams++;s.push([t.b,d+1]);}else{apps++;s.push([t.f,d+1],[t.x,d+1]);}}return{nodes,vars,lams,apps,maxDepth};}
function rawTerm(term,limit=MAX_RAW){let out='',truncated=false;const stack=[{k:'n',v:term}];const add=s=>{if(out.length+s.length>limit){out+=s.slice(0,Math.max(0,limit-out.length));truncated=true;return false;}out+=s;return true;};while(stack.length&&!truncated){const f=stack.pop();if(f.k==='t'){add(f.v);continue;}const t=f.v;if(t.t==='v'){add(String(t.i+1));continue;}if(t.t==='l'){if(!add('λ.'))break;stack.push({k:'n',v:t.b});continue;}if(!add('('))break;stack.push({k:'t',v:')'});stack.push({k:'n',v:t.x});stack.push({k:'t',v:' '});stack.push({k:'n',v:t.f});}return{text:out+(truncated?' …[truncated]':''),truncated};}
function reachableCells(closure,machine,limit=192){const seen=new Map(),q=[];if(closure)q.push(...closure.env);if(machine)for(const fr of machine.stack)if(fr.cell)q.push(fr.cell);while(q.length&&seen.size<limit){const c=q.shift();if(!c||seen.has(c.id))continue;seen.set(c.id,c);for(const x of[c.value,c.closure])if(x?.env)q.push(...x.env);}return[...seen.values()].map(c=>({id:c.id,state:c.value?'VALUE':'THUNK',env:(c.value||c.closure)?.env?.map(x=>x.id)||[]}));}
function wire(closure,machine){if(!closure)return{segments:[],nodes:0,vars:0,sampled:false,stack:[]};const st=stats(closure.term),stride=Math.max(1,Math.ceil(st.vars/MAX_WIRE));const leaves=[],lams=[],apps=[];let seenVars=0;function walk(t,path,binders,ld,ad){if(t.t==='v'){const keep=(seenVars++%stride)===0;if(!keep)return[];const i=leaves.length;leaves.push({binder:binders[t.i]??null,ad});return[i];}if(t.t==='l'){lams.push({id:path,d:ld});return walk(t.b,path+'b',[path,...binders],ld+1,ad);}const a=walk(t.f,path+'f',binders,ld,ad+1),b=walk(t.x,path+'x',binders,ld,ad+1);if(a.length&&b.length)apps.push({d:ad,a,b});return a.concat(b);}walk(closure.term,'r',[],0,0);const n=Math.max(1,leaves.length);leaves.forEach((v,i)=>v.x=n===1 ? .5 : i/(n-1));const bindMap=new Map(),lamY=new Map(),maxLam=Math.max(1,...lams.map(x=>x.d+1)),maxApp=Math.max(1,...leaves.map(x=>x.ad+1));for(const l of lams)lamY.set(l.id,.03+(l.d/maxLam)*.18);for(const v of leaves)if(v.binder){if(!bindMap.has(v.binder))bindMap.set(v.binder,[]);bindMap.get(v.binder).push(v.x);}const seg=[];for(const l of lams){const xs=bindMap.get(l.id)||[];if(xs.length)seg.push([Math.min(...xs),lamY.get(l.id),Math.max(...xs),lamY.get(l.id),0]);}for(const a of apps){const ax=a.a.map(i=>leaves[i].x),bx=a.b.map(i=>leaves[i].x),y=.26+(a.d/maxApp)*.58;seg.push([Math.min(...ax),y,Math.min(...bx),y,1]);}for(const v of leaves){const y1=v.binder?lamY.get(v.binder):.02,y2=.26+(v.ad/maxApp)*.58;seg.push([v.x,y1,v.x,Math.max(y1+.01,y2),2]);}return{segments:seg,nodes:st.nodes,vars:st.vars,sampled:stride>1,stack:machine?machine.stack.slice(-256).map(f=>f.k):[]};}

function currentClosure(machine,req,fallback){return machine?.control||req?.fn||fallback||null;}
function fastSnapshot(){const cc=currentClosure(cubeMachine,cubeReq,null),cw=currentClosure(clockState.machine,null,clockClosure);return{ts:Date.now(),clients:clients.size,clock:{time:lastClockText,beta:clockTotalBeta,rate:clockRate,done:clockState.done,wire:wire(cw,clockState.done?null:clockState.machine)},cube:{frame:cubeFrameNo,phase:cubePhase,beta:cubeBeta,rate:cubeRate,steps:cubeSteps,wire:wire(cc,cubeMachine),geometry:cubeFrame}};}
function rawSnapshot(){const cc=currentClosure(cubeMachine,cubeReq,null),cw=currentClosure(clockState.machine,null,clockClosure);return{ts:Date.now(),clock:cw?{term:rawTerm(cw.term),env:cw.env.map(c=>c.id),stack:clockState.machine?.stack?.slice(-256).map(f=>({kind:f.k,cell:f.cell.id}))||[],cells:reachableCells(cw,clockState.done?null:clockState.machine)}:null,cube:cc?{term:rawTerm(cc.term),env:cc.env.map(c=>c.id),stack:cubeMachine?.stack?.slice(-256).map(f=>({kind:f.k,cell:f.cell.id}))||[],cells:reachableCells(cc,cubeMachine)}:null};}
function send(res,event,obj){res.write(`event: ${event}\ndata: ${JSON.stringify(obj)}\n\n`);}
function broadcast(event,obj){for(const res of clients){try{send(res,event,obj);}catch{clients.delete(res);}}}
function cors(res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','content-type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');}

const server=http.createServer((req,res)=>{cors(res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}if(req.url==='/health'){res.setHeader('content-type','application/json');return res.end(JSON.stringify({ok:true,clients:clients.size,cubeFrame:cubeFrameNo,clock:lastClockText}));}if(req.url==='/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(': lambda stream\n\n');clients.add(res);send(res,'state',fastSnapshot());send(res,'raw',rawSnapshot());req.on('close',()=>clients.delete(res));return;}if(req.method==='POST'&&req.url==='/control'){let body='';req.on('data',d=>{body+=d;if(body.length>4096)req.destroy();});req.on('end',()=>{try{const x=JSON.parse(body||'{}');if(x.action==='resetCube')resetCube();if(x.action==='resetClock'){clockState=startClock();clockClosure=clockState.machine.control;lastClockText=clockState.input.text;}res.setHeader('content-type','application/json');res.end(JSON.stringify({ok:true}));}catch(e){res.writeHead(400);res.end(JSON.stringify({ok:false,error:String(e)}));}});return;}res.writeHead(404);res.end('not found');});

resetCube();
function compute(){if(clients.size){const end=performance.now()+16;while(performance.now()<end){stepClock();for(let i=0;i<12;i++)stepCube();}}else stepClock();const now=performance.now();if(now-cubeRateAt>=500){cubeRate=(cubeBeta-cubeRateBase)*1000/(now-cubeRateAt);cubeRateBase=cubeBeta;cubeRateAt=now;}if(now-clockRateAt>=500){clockRate=(clockTotalBeta-clockRateBase)*1000/(now-clockRateAt);clockRateBase=clockTotalBeta;clockRateAt=now;}setImmediate(compute);}compute();
setInterval(()=>{if(clients.size)broadcast('state',fastSnapshot());},FAST_MS);
setInterval(()=>{if(clients.size)broadcast('raw',rawSnapshot());},RAW_MS);
server.listen(PORT,'127.0.0.1',()=>console.log(`lambda backend listening on 127.0.0.1:${PORT}`));
