import {normalizeValues,sampleWave} from '../frontend/src/display/primitives.js';
import {smoothstep,smootherstep,pulse,springStep,resolveGlowStyle} from '../frontend/src/display/effects.js';
import {rasterizeDotText,scrollDotRaster} from '../frontend/src/display/dotfont.js';
import {createScene,displayLayer} from '../frontend/src/display/scene.js';
import {resolveCanvasDpr} from '../frontend/src/display/engine.js';
import {resolveHighResSize} from '../frontend/src/display/highres.js';
import {createRingBuffer,findTriggerIndex,triggerWindow} from '../frontend/src/display/scope.js';
import {sampleSignal,magnitudeSpectrum,dominantFrequency,nextPowerOfTwo,createFFTPlan,createSpectrumAnalyzer} from '../frontend/src/display/signal.js';
import {cartesianTransform} from '../frontend/src/display/plot.js';
import {rotatePoint3D,cubeProjection,cubeBeamPath} from '../frontend/src/display/cube.js';
import {measureBeamPath,sampleBeamHead,phosphorDecayForHalfLife} from '../frontend/src/display/phosphor.js';
import {PHOSPHOR_MODELS,phosphorDecayFactors,phosphorDose,phosphorRelativeEnergy} from '../frontend/src/display/phosphor-models.js';
import {measureCRTPath,sampleCRTPath,createCRTBeamState,advanceCRTBeam} from '../frontend/src/display/crt-beam.js';
const assert=(ok,message)=>{if(!ok)throw new Error(message)},close=(a,b,eps=1e-6)=>Math.abs(a-b)<=eps;
const normalized=normalizeValues([-1,0,.25,2],4);assert(normalized.length===4,'normalize length');assert(close(normalized[0],0)&&close(normalized[1],0)&&close(normalized[2],.25)&&close(normalized[3],1),'normalize clamps');
const wave=sampleWave(x=>x*2-1,5);assert(wave.length===5&&close(wave[0],-1)&&close(wave[2],0)&&close(wave[4],1),'wave sampling');
assert(close(smoothstep(0),0)&&close(smoothstep(1),1)&&close(smootherstep(0),0)&&close(smootherstep(1),1),'easing endpoints');for(let i=0;i<50;i++){const p=pulse(i/50,2);assert(p>=0&&p<=1,'pulse bounds')}
let spring={value:0,velocity:0};for(let i=0;i<240;i++)spring=springStep(spring,1,1/120,{frequency:3,damping:1});assert(Math.abs(spring.value-1)<.005,'spring converges');
const glow=resolveGlowStyle(8,{alpha:.22,quality:1});assert(glow.widthScale>1&&glow.alphaScale>0&&glow.alphaScale<1,'fast glow style');
const text=rasterizeDotText('LAMBDA'),scrolled=scrollDotRaster(text,12,3);assert(text.rows===7&&text.cols>25&&text.values.some(Boolean),'dot font');assert(scrolled.cols===12&&scrolled.values.length===84,'dot scroll');
const layer=displayLayer(()=>{}),scene=createScene(layer);assert(scene.layers.length===1,'scene composition');
const high=resolveHighResSize({width:1920,height:1080,scale:4,maxPixels:20_000_000});assert(high.pixelWidth*high.pixelHeight<=20_000_000,'high-res cap');
const live=resolveCanvasDpr({width:1000,height:500,nativeDpr:2,resolutionScale:3,maxDpr:8,maxPixels:1_000_000,quality:1});assert(live.pixelCount<=1_000_000&&live.dpr<2,'live DPR cap');const ring=createRingBuffer(4);ring.pushMany([1,2,3,4,5]);assert(ring.toArray().join(',')==='2,3,4,5','ring buffer');
const triggerSamples=[-.4,-.2,-.1,.2,.5,.3,-.2,.2];assert(findTriggerIndex(triggerSamples,{level:0,hysteresis:.01})===3,'trigger');
const typed=new Float32Array(triggerSamples),tw=triggerWindow([typed,typed],{count:5,level:0,pretrigger:.2});assert(tw[0].length===5&&ArrayBuffer.isView(tw[0]),'trigger window');
assert(nextPowerOfTwo(1000)===1024,'FFT sizing');const planA=createFFTPlan(1024),planB=createFFTPlan(1024);assert(planA===planB,'FFT cache');
const sampleRate=4096,frequency=256,samples=sampleSignal(t=>Math.sin(Math.PI*2*frequency*t),{count:1024,sampleRate}),spectrum=magnitudeSpectrum(samples,{sampleRate}),peak=dominantFrequency(spectrum);assert(Math.abs(peak.frequency-frequency)<1e-6,'FFT peak');
const analyzer=createSpectrumAnalyzer({fftSize:1024,sampleRate}),first=analyzer.analyze(t=>Math.sin(Math.PI*2*frequency*t)),values=first.values,second=analyzer.analyze(t=>Math.sin(Math.PI*2*frequency*t),{startTime:.1});assert(second.values===values,'FFT buffer reuse');
const transform=cartesianTransform({xMin:-1,xMax:1,yMin:-1,yMax:1,width:100,height:100}),origin=transform.toCanvas(0,0);assert(close(origin[0],50)&&close(origin[1],50),'Cartesian origin');
const quarter=rotatePoint3D([1,0,0],{sinZ:1,cosZ:0});assert(close(quarter[0],0)&&close(quarter[1],1),'cube rotation');
const cube=cubeProjection({sinX:0,cosX:1,sinY:0,cosY:1,sinZ:0,cosZ:1},{width:640,height:480});assert(cube.length===8&&cube.every(point=>point.every(Number.isFinite)),'cube projection');
const beamPath=cubeBeamPath([[1,0,0],[0,1,0],[0,0,1]],{width:640,height:480,blankRetrace:true}),measuredBeam=measureBeamPath(beamPath);assert(beamPath.length>=12&&measuredBeam.total>0&&beamPath.some(s=>s.blanked),'cube beam path');
const beamHead=sampleBeamHead(beamPath,.25);assert(beamHead&&Number.isFinite(beamHead.x),'beam head');
const halfLife=.24,fadeWhole=phosphorDecayForHalfLife(halfLife,halfLife),fadeHalf=phosphorDecayForHalfLife(halfLife/2,halfLife);assert(close(fadeWhole,.5,1e-9)&&close((1-fadeHalf)*(1-fadeHalf),.5,1e-9),'legacy half-life invariance');const p7=phosphorDecayFactors(1,'P7'),p31=phosphorDecayFactors(1,'P31');
assert(PHOSPHOR_MODELS.P7.halfLives[3]>PHOSPHOR_MODELS.P31.halfLives[3]&&p7[3]>p31[3],'P7 deep persistence');
const p7At15=phosphorRelativeEnergy(1.5,'P7');assert(p7At15>.0006&&p7At15<.0013,'P7 calibration near 0.1% at 1.5 seconds');
const p7Frame=phosphorDecayFactors(1/60,'P7')[2],p7Second=phosphorDecayFactors(1,'P7')[2];assert(close(p7Frame**60,p7Second,1e-9),'multi-reservoir refresh invariance');
assert(phosphorDose({beamCurrent:1,velocity:250})>phosphorDose({beamCurrent:1,velocity:2500}),'dwell-energy relation');
const crtPath=[{x1:0,y1:0,x2:100,y2:0,blanked:false},{x1:100,y1:0,x2:0,y2:100,blanked:true},{x1:0,y1:100,x2:100,y2:100,blanked:false}];
const fastRetrace=measureCRTPath(crtPath,8),slowRetrace=measureCRTPath(crtPath,2);assert(fastRetrace.total<slowRetrace.total&&Number.isFinite(sampleCRTPath(fastRetrace,.25).x),'CRT retrace timing');
const crtState=createCRTBeamState(),crtPoints=advanceCRTBeam(crtState,crtPath,1/60,{model:'P7',beamRate:1,width:200,height:200});
assert(crtPoints.length>0&&crtPoints.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.energy>=0),'analog beam stability');
console.log(`Display self-test passed; FFT=${peak.frequency}Hz; P7@1.5s=${p7At15.toFixed(6)}; P31tail=${p31[3].toFixed(4)}; CRT samples=${crtPoints.length}; cube=${cube.length}`);